### ISSUE TITLE
Bug with HTML code

### ISSUE THREAD

**Issue by KhArtNJava** [dbrain/ckeditor-syntaxhighlight#6]
Hello.
Sorry my bad English.
There is one bug:
I have some code

http://pastebin.com/LAjhBCK5

If I insert this code and save and after this open to edit - CKEditor shows in Source something like this:

http://pastebin.com/bRq6ZCxj

Can You fix this bug?

**Comment by sziegltrum** [comment]
Hi,

I tried to reconstruct your error but the code you supplied worked fine for me.
Any further informations on your problem?
